# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'News' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for News
  pod 'NVActivityIndicatorView'
  pod 'Cartography'
  pod 'XLPagerTabStrip', '~> 8.0'
  pod 'TableFlip'
  pod 'ObjectMapper', '~> 3.1'
  pod 'Alamofire'
  pod "PromiseKit"
  pod 'ParallaxHeader'
  pod 'BulletinBoard'
  pod 'SwiftyJSON'
end
